### ISSUE TITLE
大佬，现在获取不到伪装域名了

### ISSUE THREAD

**Issue by xianxin54** [k0baya/X-for-serv00#1]
之前还好好的，是serv00升级的问题吗？换了好之台机器了，还是获取不到，用自己的token也不行

**Comment by k0baya** [comment]
`ps aux`的输出，以及文件目录截图看看？你说的伪装域名是指回源的隧道域名还是cf的CDN域名？

**Comment by xianxin54** [comment]
回源隊道域名，估计是隧道的问题。以下截图
![Screenshot_20240703_044336_com termux](https://github.com/k0baya/X-for-serv00/assets/153445271/13a3a2d6-edd2-43be-a5a2-7344469683b5)

**Comment by k0baya** [comment]
> 回源隊道域名，估计是隧道的问题。以下截图 ![Screenshot_20240703_044336_com termux](https://private-user-images.githubusercontent.com/153445271/345195509-13a3a2d6-edd2-43be-a5a2-7344469683b5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NjI2NTksIm5iZiI6MTcxOTk2MjM1OSwicGF0aCI6Ii8xNTM0NDUyNzEvMzQ1MTk1NTA5LTEzYTNhMmQ2LWVkZDItNDNiZS1hNWEyLTczNDQ0Njk2ODNiNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQyMzE5MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTIyMTBlNTc2OGZmNWNkMTM3NDg1ODM0OGUzNDM4MDk5ZDFhYTdjMzc3Yjk5NGIyYWEzODBlZDBiMzViMDliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CVUdSR5OxImcuoUND4HmCviNdxHLkPAe0REIPPdzWmA)



> 回源隊道域名，估计是隧道的问题。以下截图 ![Screenshot_20240703_044336_com termux](https://private-user-images.githubusercontent.com/153445271/345195509-13a3a2d6-edd2-43be-a5a2-7344469683b5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NjI2NTksIm5iZiI6MTcxOTk2MjM1OSwicGF0aCI6Ii8xNTM0NDUyNzEvMzQ1MTk1NTA5LTEzYTNhMmQ2LWVkZDItNDNiZS1hNWEyLTczNDQ0Njk2ODNiNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQyMzE5MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTIyMTBlNTc2OGZmNWNkMTM3NDg1ODM0OGUzNDM4MDk5ZDFhYTdjMzc3Yjk5NGIyYWEzODBlZDBiMzViMDliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CVUdSR5OxImcuoUND4HmCviNdxHLkPAe0REIPPdzWmA)

我再重复一遍，请发一下`ps aux`的输出，以及文件目录截图。为了提高沟通效率，且不把issues当成版聊区域，麻烦配合一点，我不希望继续重复出现类似 [#3 ](https://github.com/k0baya/X-for-serv00/issues/3)这样浪费时间的issues。
