### ISSUE TITLE
ClashX pro或者v2rayNG连接不上

### ISSUE THREAD

**Issue by Kahen** [k0baya/X-for-serv00#10]
作者大大有空时可以帮我检查下吗？我自己看感觉没有问题，查不出来
<img width="242" alt="image" src="https://github.com/user-attachments/assets/403ef603-69db-4035-ba18-b64e96ecc3fb">
server.js配置：
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/4b2f12f5-9fb0-40b0-9b83-200fee0dd8c4">
clash 配置：
<img width="396" alt="image" src="https://github.com/user-attachments/assets/8aae9252-3a4c-47b3-9d1f-2f0facf7eab9">
cloudflare显示active：
<img width="1468" alt="image" src="https://github.com/user-attachments/assets/1138b76f-275b-43bc-8642-1f45bec34c0a">
ps aux输出：
<img width="1711" alt="image" src="https://github.com/user-attachments/assets/b77ff4c1-9e54-47be-a831-44871b8d1da1">

**Comment by k0baya** [comment]
请自行优选 Cloudflare CDN 域名或者 IP 替换客户端内的配置地址 `alejandracaiccedo.com:443` 。该域名已在中国大陆部分地区被阻断。
