### ISSUE TITLE
可以连接网速慢几乎没法用（固定隧道和临时隧道都慢）

### ISSUE THREAD

**Issue by sunboy0523** [k0baya/X-for-serv00#11]
您好，部署成功后，可以连接，但是网速非常差，几乎没法用，家里移动宽带和手机联通数据测试都慢

**Comment by k0baya** [comment]
您好，

感谢您的反馈和支持。对于您提到的连接成功但网速非常差的问题，我们建议您考虑使用付费机场。这些服务通常在带宽和稳定性方面有更好的保障，可以提供更优质的翻墙体验。

自行部署虽然可以节省部分费用，但由于网络环境和设备配置的差异，可能无法达到理想的速度和稳定性。专业的付费服务通常会有专门的技术团队进行维护和优化，能够更好地满足您的使用需求。

感谢您的理解，希望能帮助到您。

祝好！

**Comment by sunboy0523** [comment]
> 您好，
> 
> 感谢您的反馈和支持。对于您提到的连接成功但网速非常差的问题，我们建议您考虑使用付费机场。这些服务通常在带宽和稳定性方面有更好的保障，可以提供更优质的翻墙体验。
> 
> 自行部署虽然可以节省部分费用，但由于网络环境和设备配置的差异，可能无法达到理想的速度和稳定性。专业的付费服务通常会有专门的技术团队进行维护和优化，能够更好地满足您的使用需求。
> 
> 感谢您的理解，希望能帮助到您。
> 
> 祝好！

谢谢，我就是一直关注您的博客发现更新了，看介绍网络不错，就想着试试看，结果不理想，还一直怀疑是自己部署有问题，那应该是这个服务器本身网络就不稳定

**Comment by k0baya** [comment]
> > 您好，
> > 感谢您的反馈和支持。对于您提到的连接成功但网速非常差的问题，我们建议您考虑使用付费机场。这些服务通常在带宽和稳定性方面有更好的保障，可以提供更优质的翻墙体验。
> > 自行部署虽然可以节省部分费用，但由于网络环境和设备配置的差异，可能无法达到理想的速度和稳定性。专业的付费服务通常会有专门的技术团队进行维护和优化，能够更好地满足您的使用需求。
> > 感谢您的理解，希望能帮助到您。
> > 祝好！
> 
> 谢谢，我就是一直关注您的博客发现更新了，看介绍网络不错，就想着试试看，结果不理想，还一直怀疑是自己部署有问题，那应该是这个服务器本身网络就不稳定

快慢只取决于你和默认 CDN 地址 `alejandracaiccedo.com:443` 的连接速率，可以仅在客户端修改 CDN 地址提升速度。优选 CF CDN 已经有很多成熟的方案，可以自己查一下。
