### ISSUE TITLE
关于保活

### ISSUE THREAD

**Issue by Ethangoin** [k0baya/X-for-serv00#15]
终于还是通了，速度时快时慢，估计和优选ip有关，但是保存活那条重启代码有个疑问：
/home/username/domains/argo-x/start.sh >/dev/null 2>&1，
domains里找不到argo-x文件夹，更找不到start.sh啊？把username换成自已的用户名在ssh客户端里运行也会报：start.sh: No such file or directory，请教怎么回事？

**Comment by k0baya** [comment]
![image](https://github.com/user-attachments/assets/add15983-f37c-4c50-a3ba-c45e2d9718f1)
你的 `start.sh` 在哪里就怎么填。
