### ISSUE TITLE
xray可以部署成像https://github.com/yixiu001/serv00-script这个库节点地址为用户域名的方案吗？免被墙

### ISSUE THREAD

**Issue by sunboy0523** [k0baya/X-for-serv00#16]
您好，xray可以部署成https://github.com/yixiu001/serv00-script像这个库节点地址为用户域名的方案吗？这个库好像是nodejs部署的ws协议，节点地址是用户域名，国内可以访问，并且网速有个一般，应急可以备用，xray可以部署成节点地址是用户域名的方案吗？如果可以singbox是不是也行？谢谢大佬。

**Comment by k0baya** [comment]
不作提供，您提供的仓库的作者在 ytb 发布的视频涉嫌严重抄袭，如有需要请直接找他本人。

**Comment by k0baya** [comment]
另外用户域名和 webX.serv00.com 为同一 IP，本仓库直连分支早就为三种协议都提供了三个不同 IP 的接入方案，如果在你的地区九条线路无一条可用，那么用户域名也不可能可用。

**Comment by sunboy0523** [comment]
> 另外用户域名和 webX.serv00.com 为同一 IP，本仓库直连分支早就为三种协议都提供了三个不同 IP 的接入方案，如果在你的地区九条线路无一条可用，那么用户域名也不可能可用。

好的，谢谢，我用您的直连分支也部署过，确实webX.serv00.com和cacheX.serv00.com都可以连通，但同一个服务器，都是vless节点，网速好像没有另外那个库的ws传输协议快，不知道是不是个例，或者今天恰好网络比较好。

**Comment by k0baya** [comment]
> > 另外用户域名和 webX.serv00.com 为同一 IP，本仓库直连分支早就为三种协议都提供了三个不同 IP 的接入方案，如果在你的地区九条线路无一条可用，那么用户域名也不可能可用。
> 
> 好的，谢谢，我用您的直连分支也部署过，确实webX.serv00.com和cacheX.serv00.com都可以连通，但同一个服务器，都是vless节点，网速好像没有另外那个库的ws传输协议快，不知道是不是个例，或者今天恰好网络比较好。

建议自己 Google 一下 vless-ws 和 vless-reality，了解一下有哪些不同。
