### ISSUE TITLE
设置的cron job无效

### ISSUE THREAD

**Issue by Myuuer** [k0baya/X-for-serv00#17]
![1](https://github.com/user-attachments/assets/08e1c56a-f5bf-41d4-991f-0a9a462057d9)
![2](https://github.com/user-attachments/assets/0143b0fd-8d5b-4a68-a9c7-dcd657037add)
设置的cron job无效，请帮忙看下这个命令是否正确

**Comment by k0baya** [comment]
路径写错了，请写正确的绝对路径。

**Comment by Myuuer** [comment]
绝对路径是啥啊，指点一下
这个项目变了，我在另一个项目中
/domains/myuuer1.serv00.net/sing-box/start.sh >/dev/null 2>&1
/home/myuuer1/domains/myuuer1.serv00.net/sing-box/start.sh >/dev/null 2>&1
都试了没用。

**Comment by k0baya** [comment]
这种问题 GPT 一下都能解决的。按照你的截图，你的 `start.sh` 的绝对路径为：
```
/home/用户名/domains/myuuer0.serv00.net/xray/start.sh
```
你一会儿 `myuuer0` 一会 `myuuer1` 的我也不清楚你的用户名到底是什么。

另外既然已经更新，统一建议使用新版本，在一键安装脚本的帮助下，就不需要弄明白什么是绝对路径。
