### ISSUE TITLE
大佬，安装环境提示依赖包下载网络异常

### ISSUE THREAD

**Issue by Waawww** [k0baya/X-for-serv00#19]
s8服务器，安装过程中：
```
正在安装依赖...
--2024-08-02 17:03:36--  https://cloudflared.bowring.uk/binaries/cloudflared-freebsd-latest.7z
Resolving cloudflared.bowring.uk (cloudflared.bowring.uk)... 127.0.0.11
Connecting to cloudflared.bowring.uk (cloudflared.bowring.uk)|127.0.0.11|:443... failed: Can't assign requested address.
Retrying.
```
安装结束，可以正常看到/status和/list，请问可以如何处理啊？能换个地址或者手动上传吗？

**Comment by k0baya** [comment]
说明目前 S8 已对下载 Cloudflared 客户端的网址进行了 host 阻断。你可以等待 S8 阻断结束后再次尝试或者换一个 Server 进行部署。

同时，你不应该在 `/status` 下没有出现两个相关进程时直接进入 `/list` 路径，这会引起一些错误。

如果你能看得明白，也可以按照如下操作手动下载 Cloudflared 客户端并上传到相应位置：

首先下载 `https://cloudflared.bowring.uk/binaries/cloudflared-freebsd-latest.7z` 并解压，然后将解压出来的 Cloudflared 二进制文件上传到你的 Serv00 内的这个路径：`/home/LOGIN/domains/LOGIN.serv00.net/public_nodejs`

并使用 `chmod` 指令给 cloudflared 二进制文件添加可执行权限。

接着执行命令：`killall -u $(whoami)`

然后重新进入网页的 `/status` 刷新并等待两个相关进程的启动。

**Comment by AkenClub** [comment]
> 说明目前 S8 已对下载 Cloudflared 客户端的网址进行了 host 阻断。你可以等待 S8 阻断结束后再次尝试或者换一个 Server 进行部署。
> 
> 同时，你不应该在 `/status` 下没有出现两个相关进程时直接进入 `/list` 路径，这会引起一些错误。
> 
> 如果你能看得明白，也可以按照如下操作手动下载 Cloudflared 客户端并上传到相应位置：
> 
> 首先下载 `https://cloudflared.bowring.uk/binaries/cloudflared-freebsd-latest.7z` 并解压，然后将解压出来的 Cloudflared 二进制文件上传到你的 Serv00 内的这个路径：`/home/LOGIN/domains/LOGIN.serv00.net/public_nodejs`
> 
> 并使用 `chmod` 指令给 cloudflared 二进制文件添加可执行权限。
> 
> 接着执行命令：`killall -u $(whoami)`
> 
> 然后重新进入网页的 `/status` 刷新并等待两个相关进程的启动。

补充一下，下载的文件一般名为：`cloudflared-freebsd-xxx`，上传到你自己网站的public_nodejs后需要改名为：cloudflared，并给权限。之后在按作者的提示操作。
在 argo.sh 文件里面有判断文件是否存在。
`[ ! -e ${WORKDIR}/cloudflared ] && check_file`

![image](https://github.com/user-attachments/assets/60ff010b-2127-4504-b033-6743fbdd0f0d)
