### ISSUE TITLE
dns 的问题？

### ISSUE THREAD

**Issue by gitG0hub** [k0baya/X-for-serv00#2]
用的是ssforandroid,配置用了argo,但是解析不出来不知道是不是被墙了

**Comment by gitG0hub** [comment]
![Screenshot_20240702-094132_Shadowsocks](https://github.com/k0baya/X-for-serv00/assets/65051091/d4bfcb6d-32c9-4a4a-9b44-fa8e12c8cc7b)

**Comment by k0baya** [comment]
本仓库的代理路径是：

本地 → Cloudflare CDN → serv00 → 目标网站

DNS 服务器是 `1.1.1.1` 和 `8.8.8.8`，没有任何问题。

如果你连不上，可能是我填写的默认 Cloudflare CDN 域名（alejandracaiccedo.com）在你的地区被阻断，你可以自己尝试把 Server 替换成任意 Cloudflare CDN 域名或者 IP ，可以参考仓库：[XIU2/CloudflareSpeedTest](https://github.com/XIU2/CloudflareSpeedTest) 替换成你本地网络连接速度最快的 Cloudflare CDN。

但是你的截图里分明显示有流量在跑，只是 HTTP 测速点没连上，请访问 `https://whatismyip.com` 之类的网址查证代理是否成功。另外，Sing-box 核心的代理软件对本仓库适配不太好，请尝试使用其他核心的代理软件测试。

**Comment by gitG0hub** [comment]
![Screenshot_20240702-141328_Kiwi Browser](https://github.com/k0baya/X-for-serv00/assets/65051091/84eadb02-ecdc-4d2f-951e-e6fdd61e7ce5)
![Screenshot_20240702-141139_Kiwi Browser](https://github.com/k0baya/X-for-serv00/assets/65051091/e0fc0e1a-ef46-4b4f-abea-7db3ae34093b)
![Screenshot_20240702-141338_Shadowsocks](https://github.com/k0baya/X-for-serv00/assets/65051091/601d438d-06fa-4bb1-bafe-ef7e533fb890)
你好👋，在不连接的时候该域名是可以打开的，但是连接之后有流量，但是网站确实是打不开的报错是errname,所以我怀疑是dns的问题，在更换优选ip为server的时候，是同样的结果，请问我应该如何解决？

**Comment by gitG0hub** [comment]
![Screenshot_20240702-141718_Kiwi Browser](https://github.com/k0baya/X-for-serv00/assets/65051091/fb12b855-6b96-4ae6-80b1-ebc324617f2a)
