### ISSUE TITLE
遇到不让输入直接跳过报错的问题

### ISSUE THREAD

**Issue by ivyxyc** [k0baya/X-for-serv00#20]
大佬，遇到了不让输入参数直接就跳到最后报错的问题，求解答
![Screenshot_2024-08-04-10-41-48-946_com sonelli juicessh-edit](https://github.com/user-attachments/assets/bb93f624-80c9-4887-ba39-b688c08d3051)

**Comment by StudyingLover** [comment]
same

**Comment by k0baya** [comment]
我的错，不该把那个命令 base64 一次，请直接使用命令：
```
bash <(curl -Ls https://raw.githubusercontent.com/k0baya/x-for-serv00/main/entrypoint.sh)
```
