### ISSUE TITLE
貌似有下载的报错

### ISSUE THREAD

**Issue by huomqh** [k0baya/X-for-serv00#21]
正在安装依赖...
--2024-08-04 07:22:30--  https://cloudflared.bowring.uk/binaries/cloudflared-freebsd-latest.7z
Resolving cloudflared.bowring.uk (cloudflared.bowring.uk)... 127.0.0.11
Connecting to cloudflared.bowring.uk (cloudflared.bowring.uk)|127.0.0.11|:443... failed: Can't assign requested address.
Retrying.

--2024-08-04 07:22:31--  (try: 2)  https://cloudflared.bowring.uk/binaries/cloudflared-freebsd-latest.7z
Connecting to cloudflared.bowring.uk (cloudflared.bowring.uk)|127.0.0.11|:443... failed: Can't assign requested address.
Retrying.

--2024-08-04 07:22:33--  (try: 3)  https://cloudflared.bowring.uk/binaries/cloudflared-freebsd-latest.7z
Connecting to cloudflared.bowring.uk (cloudflared.bowring.uk)|127.0.0.11|:443... failed: Can't assign requested address.
Retrying.

--2024-08-04 07:22:36--  (try: 4)  https://cloudflared.bowring.uk/binaries/cloudflared-freebsd-latest.7z
Connecting to cloudflared.bowring.uk (cloudflared.bowring.uk)|127.0.0.11|:443... failed: Can't assign requested address.
Retrying.

--2024-08-04 07:22:40--  (try: 5)  https://cloudflared.bowring.uk/binaries/cloudflared-freebsd-latest.7z
Connecting to cloudflared.bowring.uk (cloudflared.bowring.uk)|127.0.0.11|:443... failed: Can't assign requested address.

**Comment by huomqh** [comment]
按照https://github.com/k0baya/X-for-serv00/issues/19这里说的，把二进制文件上传，并chmod给了777权限，运行脚本还是报错
![Snipaste_2024-08-04_13-44-09](https://github.com/user-attachments/assets/10dd3967-3780-444b-9a5e-d2bcf8a20ec3)
![Snipaste_2024-08-04_13-44-54](https://github.com/user-attachments/assets/8567eed1-aaab-4823-8529-e035dd99c984)

**Comment by k0baya** [comment]
> 按照[https://github.com/k0baya/X-for-serv00/issues/19这里说的，把二进制文件上传，并chmod给了777权限，运行脚本还是报错](https://github.com/k0baya/X-for-serv00/issues/19%E8%BF%99%E9%87%8C%E8%AF%B4%E7%9A%84%EF%BC%8C%E6%8A%8A%E4%BA%8C%E8%BF%9B%E5%88%B6%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0%EF%BC%8C%E5%B9%B6chmod%E7%BB%99%E4%BA%86777%E6%9D%83%E9%99%90%EF%BC%8C%E8%BF%90%E8%A1%8C%E8%84%9A%E6%9C%AC%E8%BF%98%E6%98%AF%E6%8A%A5%E9%94%99) ![Snipaste_2024-08-04_13-44-09](https://private-user-images.githubusercontent.com/20906294/354878987-10dd3967-3780-444b-9a5e-d2bcf8a20ec3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NTQ5NDEsIm5iZiI6MTcyMjc1NDY0MSwicGF0aCI6Ii8yMDkwNjI5NC8zNTQ4Nzg5ODctMTBkZDM5NjctMzc4MC00NDRiLTlhNWUtZDJiY2Y4YTIwZWMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDA2NTcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhOWJiMjlkZDk1YjM1YjBmN2FiMGVkMThkNDQxOTQ1ZDYwYzMxYzU5MTExNmVjZTVjMGZjZWU0OTkzYmI1NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o4MOkbZdNNvgMEjMX7ZFGEinnAjhDH6Q2mbjJirNJVk) ![Snipaste_2024-08-04_13-44-54](https://private-user-images.githubusercontent.com/20906294/354878993-8567eed1-aaab-4823-8529-e035dd99c984.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NTQ5NDEsIm5iZiI6MTcyMjc1NDY0MSwicGF0aCI6Ii8yMDkwNjI5NC8zNTQ4Nzg5OTMtODU2N2VlZDEtYWFhYi00ODIzLTg1MjktZTAzNWRkOTljOTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDA2NTcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlYzQ0ZGQ2ZWFiN2ViZTRjZTY4NTA5YTcwNThlMGY4OGVlNmFjZDY5OTJjNDQwODk1OTczN2RmMzVlNWQyODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V6vqOOTvS9Q0fPqOJAZklIqeMP4I8n5JNkCwwhTfNDs)

重命名为cloudflared。
