### ISSUE TITLE
尝试添加预留端口是一个一个递减尝试的吗

### ISSUE THREAD

**Issue by rgj226** [k0baya/X-for-serv00#23]
<img width="675" alt="图片" src="https://github.com/user-attachments/assets/c269d885-a557-47c5-b2dd-ec1c8217100e">
这得要好久，能不能随机

**Comment by k0baya** [comment]
你可以选择自己去面板里添加，面板里的随机端口可以避开已被占用的端口。命令行没有随机选项，只能伪随机，无法避开已被占用端口，意义不大。
