### ISSUE TITLE
web.js进程启动失败

### ISSUE THREAD

**Issue by sunboy0523** [k0baya/X-for-serv00#24]
最新直连版，部署无任何异常提示，但web.js进程没有正常启动，刷新多次都没用

**Comment by k0baya** [comment]
ssh 连接，进入 `/home/LOGIN/domains/LOGIN.serv00.net/public_nodejs` 路径，执行命令 `./web.js -c config.json` 有什么提示？

**Comment by sunboy0523** [comment]
> ssh 连接，进入 `/home/LOGIN/domains/LOGIN.serv00.net/public_nodejs` 路径，执行命令 `./web.js -c config.json` 有什么提示？

Xray 1.8.23 (Xray, Penetrates Everything.) 4c82ef8 (go1.22.5 freebsd/amd64)
A unified platform for anti-censorship.
Failed to start: app/proxyman/inbound: failed to listen TCP on 63932 > transport/internet: failed to listen on address: 0.0.0.0:63932 > transport/internet/tcp:
failed to listen TCP on 0.0.0.0:63932 > listen tcp 0.0.0.0:63932: bind: address
already in use

**Comment by k0baya** [comment]
你运行了其他什么进程？输入命令 `ps aux` 看看。

**Comment by k0baya** [comment]
本项目只为单账号运行设计，账号里不得运行其他任何程序。请新建账号单独部署本项目。
