### ISSUE TITLE
脚本要求输入serv00密码

### ISSUE THREAD

**Issue by aw12aw2021** [k0baya/X-for-serv00#25]
是不是账号的登录密码?

我第一次随便输入一个  脚本正在尝试生成配置... 15分钟都没完成
第二次跑  没要求输入密码了  脚本跑到正在尝试生成配置...   20分钟还没完成

**Comment by k0baya** [comment]
就是登录密码。除了登录密码以外，应该没有别的密码了吧。请执行 `rm -rf ~/domains`，再去面板里删掉所有的 www websites，然后重新尝试安装。
