### ISSUE TITLE
脚本跑完没有报错，但是 web.js cloudflared 进程都没有起来

### ISSUE THREAD

**Issue by toou1234** [k0baya/X-for-serv00#26]
手动启了 web.js 也没有任何报错

**Comment by huomqh** [comment]
是不是panel8？好像我感觉是服务器封了这个脚本

**Comment by toou1234** [comment]
> 是不是panel8？好像我感觉是服务器封了这个脚本

对 是8

**Comment by k0baya** [comment]
请附上网页和ps aux的截图。

**Comment by nathan-ey** [comment]
![微信图片_20240808015734](https://github.com/user-attachments/assets/f4fcd0eb-89f0-434a-a47d-b3b8104d7bf9)

大佬好，我安装完成后，按提示访问  /status 和 /list访问两个 页面，不知道怎么都提示下面这个报错页面
？是安装少了什么步骤吗？

![微信截图_20240808015803](https://github.com/user-attachments/assets/cab03d78-9347-400a-a451-8c4664cc6977)

环境：panel8 主机

CF三个固定通道已经配置好了。
![微信截图_20240808020210](https://github.com/user-attachments/assets/84613576-6b12-4ea3-a87f-0404bbc9751c)

**Comment by k0baya** [comment]
出现这种情况，就表明你部署过一遍后，然后把文件夹整个删掉重新部署了一遍。
能好好用就不要这样折腾，非要这样整，那就删完文件后去面板里把所有的 www websites 都删掉再重新部署。

**Comment by aw12aw2021** [comment]
这种情况是cloudflared内核没下载  造成的  

另外请开发哥哥出一键清除命令  方便输错的时候重新跑脚本

**Comment by 1614229132** [comment]
![image](https://github.com/user-attachments/assets/3034d577-b2de-45bc-87a2-ba526d124510)
我也遇到了这个问题，www websites删掉，并且清服务器所有文件后，执行依旧有这个问题，并且隧道为降级状态

**Comment by maricruzy** [comment]
那个clodflare下载很慢,一直那样,可以上传上吗?

**Comment by k0baya** [comment]
> 那个clodflare下载很慢,一直那样,可以上传上吗?

![image](https://github.com/user-attachments/assets/51a68b0b-a046-4198-9101-fb68b30caef6)
https://github.com/k0baya/X-for-serv00?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
有问题先看 readme，readme 没写的欢迎提问，用以补充 readme。
