### ISSUE TITLE
web.js能启动，但是cloudflare就是起不来

### ISSUE THREAD

**Issue by huomqh** [k0baya/X-for-serv00#27]
panel8的账户，不懂为啥了~这个cloudflare文件是我从panel0服务器上拉下来确定能用的版本
![Snipaste_2024-08-08_15-03-39](https://github.com/user-attachments/assets/b4c7cb94-5a22-450c-b74c-30c4b9935f28)
![Snipaste_2024-08-08_15-04-24](https://github.com/user-attachments/assets/a960e53e-5283-4142-b2da-dcce324ffd3f)
![Snipaste_2024-08-08_15-04-43](https://github.com/user-attachments/assets/734d8f7d-86e8-4c82-a142-e78847e19565)
![Snipaste_2024-08-08_15-06-27](https://github.com/user-attachments/assets/6fa7d636-77a1-4fca-b0e9-9224cd2a0a50)

**Comment by k0baya** [comment]
`chmod -R 777 ~/domains && killall -u $(whoami)`
执行完上述命令回到网页的 /status 下，刷新并等待一分钟左右，再刷新看看 cloudflared 有没有起来。

**Comment by huomqh** [comment]
> `chmod -R 777 ~/domains && killall -u $(whoami)` 执行完上述命令回到网页的 /status 下，刷新并等待一分钟左右，再刷新看看 cloudflared 有没有起来。

这么做果然起来了，大佬牛逼！！
