### ISSUE TITLE
修改app.js 49行处的代码就可以解决用户名带有大写字母的账户运行出错的问题

### ISSUE THREAD

**Issue by LeeDespo** [k0baya/X-for-serv00#28]
佬，我发现大小写的问题所在了。您在app.js的49行代码如下：
const WORKDIR = path.join('/home', USERNAME, 'domains', `${USERNAME}.serv00.net`, 'public_nodejs');
需要改为：
const WORKDIR = path.join('/home', USERNAME, 'domains', `${os.userInfo().username.toLowerCase()}.serv00.net`, 'public_nodejs');

**Comment by k0baya** [comment]
[e9069cd](https://github.com/k0baya/X-for-serv00/commit/e9069cd5939f8646072b45b0d3db957a4cb286f9)
