### ISSUE TITLE
建议对保活的介绍详细些

### ISSUE THREAD

**Issue by maricruzy** [k0baya/X-for-serv00#29]
自动启动

此次版本更新之后，X-for-Serv00 已经可以摆脱 Serv00 的 Crontab 启动，你可以通过访问网页对项目进行唤醒，如果你需要保活，可以使用以下公共服务对网页进行监控：

1 [cron-job.org](https://console.cron-job.org/)

2 [UptimeRobot](https://uptimerobot.com/)

同时，你也可以选择自建 [Uptime-Kuma](https://github.com/louislam/uptime-kuma) 等服务进行监控。

    建议监控 /info 路径，因为该路径无需身份验证。

    不要监控根路径，因为根路径为静态页面，只是该项目的伪装，无法起到保活效果。

能不能保活的介绍详细些?谢谢

**Comment by k0baya** [comment]
你有什么看不明白的你直接说，我不知道有哪里难以理解的。

**Comment by maricruzy** [comment]
请教下，使用[UptimeRobot](https://uptimerobot.com/)保活，在[UptimeRobot](https://uptimerobot.com/)网站添加监视，如1.serv00.net/info是否可以保活？
另外，在[UptimeRobot](https://uptimerobot.com/)网站添加监视panel8.serv00.com,可以保活吗?

**Comment by k0baya** [comment]
> 请教下，使用[UptimeRobot](https://uptimerobot.com/)保活，在[UptimeRobot](https://uptimerobot.com/)网站添加监视，如1.serv00.net/info是否可以保活？ 另外，在[UptimeRobot](https://uptimerobot.com/)网站添加监视panel8.serv00.com,可以保活吗?

你监控面板干嘛，比如你的 serv00 用户为`LOGIN`，那么你可以在`https://LOGIN.serv00.net/list`获取到导出的配置，同理`https://LOGIN.serv00.net/info`就是用来监控的页面。这个很难理解么？

**Comment by maricruzy** [comment]
也就是说https://LOGIN.serv00.net/info是用来监控的页面,用[UptimeRobot](https://uptimerobot.com/)监控并不能保活?可以这样理解吗?大佬

**Comment by k0baya** [comment]
是我表达有问题吗？意思是你可以使用任意网站监控，比如公共的 Uptime-Robot 或者 cron-job.org 以及自己搭建的 Uptime-Kuma 等等，监控 `/info` 页面，对本项目实现保活，这个没能理解吗？

**Comment by maricruzy** [comment]
明白了,谢谢
