### ISSUE TITLE
还是连不上

### ISSUE THREAD

**Issue by gitG0hub** [k0baya/X-for-serv00#3]
由于旧帖关闭重发一贴，👋作者，我在没有连接的情况的，是可以打开你的地址的，但是连接之后呢确实是有流量但是打开所有网页都报错err name，所以怀疑是dns出现问题，优选ip过后也是一样结果，应该如何解决呢？更换成v2rayng又是报错closepipe
![Screenshot_20240702-141718_Kiwi Browser](https://github.com/k0baya/X-for-serv00/assets/65051091/dca99647-fdcc-4b0c-9b5a-be303458b1a1)
![Screenshot_20240702-142433_v2rayNG](https://github.com/k0baya/X-for-serv00/assets/65051091/a045f45a-1546-4656-b0ef-7498292d8ee1)
![Screenshot_20240702-141338_Shadowsocks](https://github.com/k0baya/X-for-serv00/assets/65051091/1275a367-e3ab-4ef2-b1b3-851275b89b40)
![Screenshot_20240702-141328_Kiwi Browser](https://github.com/k0baya/X-for-serv00/assets/65051091/992e1783-5055-41be-b901-7baa03e8ed98)
![Screenshot_20240702-141319_X浏览器](https://github.com/k0baya/X-for-serv00/assets/65051091/58ec67e8-ea75-4c72-a05a-4c2be7ee8d14)
![Screenshot_20240702-141139_Kiwi Browser](https://github.com/k0baya/X-for-serv00/assets/65051091/b8a8401f-0a8b-40dc-99f6-11bd14eb86ca)
![Screenshot_20240702-141131_Kiwi Browser](https://github.com/k0baya/X-for-serv00/assets/65051091/de5aa5f9-d88b-4325-b420-2dd395d5f023)

**Comment by k0baya** [comment]
你确定你的 serv00 账户上，x-for-serv00 的相关进程还在正常运行？
我已经告诉了你和 DNS 无关，如果你坚持是 DNS 问题，你可以尝试自己修改 DNS 并发起 Pull Request。

**Comment by gitG0hub** [comment]
我不是很懂这些，我只是不知道怎么搞好，服务是开启的，list可以正常显示的

**Comment by k0baya** [comment]
> 我不是很懂这些，我只是不知道怎么搞好，服务是开启的，list可以正常显示的

看一下，把 /list 换成 /status，然后把网页里的全部内容复制过来。

**Comment by gitG0hub** [comment]
![IMG_20240702_171836](https://github.com/k0baya/X-for-serv00/assets/65051091/fa84859c-73b7-4feb-a264-d14f8f191f79)

**Comment by k0baya** [comment]
> ![IMG_20240702_171836](https://private-user-images.githubusercontent.com/65051091/344960854-fa84859c-73b7-4feb-a264-d14f8f191f79.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTIzNDEsIm5iZiI6MTcxOTkxMjA0MSwicGF0aCI6Ii82NTA1MTA5MS8zNDQ5NjA4NTQtZmE4NDg1OWMtNzNiNy00ZmViLWEyNjQtZDE0ZjhmMTkxZjc5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA5MjA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhNWJlMGU5NGViNGRmZTk3MzRkOWQzYWJiNGUyMWEzYjQ2NGZkY2YzZGRiNGIwN2Q3YTIwNjhkZGJjZjRmYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._EfZvwqdq3XHTmroqmE-UXxSqixiI3mKptwuIKR3H78)

`cat nohup.out` 和 `cat config,json` 看一眼。

**Comment by gitG0hub** [comment]
![Screenshot_20240702-172740_Termius](https://github.com/k0baya/X-for-serv00/assets/65051091/72200701-5645-4ad0-9a19-6866e6b0238d)

**Comment by gitG0hub** [comment]
![Screenshot_20240702-172721_Termius](https://github.com/k0baya/X-for-serv00/assets/65051091/9f7c43cc-8b23-47ce-81c4-e6bbfca3d105)

**Comment by k0baya** [comment]
爱莫能助，你的截图总是不能呈现关键信息，无论是我希望你上 /status 复制全文，还是config.json的入站部分，都看不到。请问你具体填入了哪几个环境变量？是否固定了argo 隧道？光就你给我的不完整信息来看，没有问题。

**Comment by gitG0hub** [comment]
![Screenshot_20240702-172719_Termius](https://github.com/k0baya/X-for-serv00/assets/65051091/d165c848-213b-4796-a9ed-083472f3226c)

**Comment by gitG0hub** [comment]
![Screenshot_20240702-173833_MT管理器](https://github.com/k0baya/X-for-serv00/assets/65051091/dd032ce8-8897-48a5-9ab3-e4ac321887c1)

**Comment by k0baya** [comment]
你固定了 argo 隧道，那么你在cf的面板中把你这个 argo 隧道的域名指向了 HTTP://localhost:VMPORT 吗？

**Comment by gitG0hub** [comment]
这好像有点问题哈
![Screenshot_20240702-175927_Kiwi Browser](https://github.com/k0baya/X-for-serv00/assets/65051091/a666596e-b9b2-4ca2-aac0-295a8fe4392d)

**Comment by k0baya** [comment]
> 这好像有点问题哈 ![Screenshot_20240702-175927_Kiwi Browser](https://private-user-images.githubusercontent.com/65051091/344975583-a666596e-b9b2-4ca2-aac0-295a8fe4392d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTUxMzcsIm5iZiI6MTcxOTkxNDgzNywicGF0aCI6Ii82NTA1MTA5MS8zNDQ5NzU1ODMtYTY2NjU5NmUtYjliMi00Y2EyLWFhYzAtMjk1YThmZTQzOTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDEwMDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ZjM3ZjU2NWQ0Mzk3YTM5YzA0YjFhZTBlMjczMGNkOWU4MmQ2MzRjYmU1N2Q0NzUzYmRkZjJlM2I1ZjgyZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._4ffhnkkbKFR5wae9bbhBr0s_zr3Zl-1uAiD_W6uavA)

请分清楚这两个变量：`VMPORT`和`WEBPORT`，注意是HTTP://localhost:VMPORT

请好好阅读readme，并检查自己的设置是否正确。这种低级错误发issues我是真的很无奈。

**Comment by gitG0hub** [comment]
不好意思，在改正并且重启之后，任然是相同情况，还有一点就是，在该和不该之后，连接后访问主机地址会出现cloudflare的400或者404,其他网址是没办法访问的

**Comment by gitG0hub** [comment]
![Screenshot_20240702-182200_Kiwi Browser](https://github.com/k0baya/X-for-serv00/assets/65051091/567d4b12-48d2-4e79-bc5c-41ea1afd9764)

**Comment by k0baya** [comment]
> ![Screenshot_20240702-182200_Kiwi Browser](https://private-user-images.githubusercontent.com/65051091/344983161-567d4b12-48d2-4e79-bc5c-41ea1afd9764.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MTYzODIsIm5iZiI6MTcxOTkxNjA4MiwicGF0aCI6Ii82NTA1MTA5MS8zNDQ5ODMxNjEtNTY3ZDRiMTItNDhkMi00ZTc5LWJjNWMtNDFlYTFhZmQ5NzY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDEwMjgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5ZWFkNWZmZDdlNzI5NTNhM2IyZjM5Y2U2YjQwZGJiODU2NDAxYzQyNDU4NDJkNGMzZjU1Zjc5MTA0YTY5NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FpcCk_ItOPr6E5W4HDVSZI-H9N7H_RuwPdq8AiXB9OA)

![Screenshot_2024-07-02-18-31-41-31_a252b927494330cdc2c8ba3b3f952e5e](https://github.com/k0baya/X-for-serv00/assets/132335755/5dbbe443-9778-49cc-9a44-2e19a3ce99ab)

我是不知道你是怎么搞的，首先我都打得开，其次，我输入了上面你的用户名和密码后测了一下里面的配置，都是通的了。

**Comment by gitG0hub** [comment]
你安卓用的啥客户端呀，是可以连接了的意思吗

**Comment by k0baya** [comment]
> 你安卓用的啥客户端呀，是可以连接了的意思吗

对啊，就是可以用了。测试用客户端是：
https://github.com/2dust/v2rayNG

**Comment by gitG0hub** [comment]
现在行吗，你用我这配置打开个网页试试行吗

**Comment by gitG0hub** [comment]
我也用的这个呀

**Comment by gitG0hub** [comment]
wc,活了活了，wc感谢大佬，wcwc

**Comment by k0baya** [comment]
> 现在行吗，你用我这配置打开个网页试试行吗

哥，我都说了我测了能用，你咋这么麻烦啊？
