### ISSUE TITLE
连接意外终止

### ISSUE THREAD

**Issue by ClayCoffee** [k0baya/X-for-serv00#30]
![X8F1C)_B)_XWMW3X%$J@(2](https://github.com/user-attachments/assets/f6a2e622-bfd6-48bc-b437-c49479bdc66e)
# ps aux

USER          PID %CPU %MEM     VSZ   RSS  TT  STAT STARTED    TIME COMMAND  
*114514 56673  0.0  0.0  678980 78092   -  S    09:46   0:05.89 node22: v22.4.1 idle *114514.serv00  
*114514 58438  0.0  0.0 1255296 27680   -  I    09:47   0:00.06 ./web.js -c ./config.json  
*114514 62934  0.0  0.0 1262892 43780   -  I    09:47   0:00.40 ./cloudflared tunnel --edge-ip-version auto --protocol http2 run --token [REDACTED]
*114514 65559  0.0  0.0   23064 12620   -  SN   09:47   0:00.12 sshd: *114514@pts/854 (sshd)  
*114514  1196  0.0  0.0   13532  3300 854  RN+  10:10   0:00.01 ps aux  
*114514 65667  0.0  0.0   14776  4764 854  SNs  09:47   0:00.06 -bash (bash)  

# cloudflare
![KKR)W29OAVT$@~X6}J459RQ](https://github.com/user-attachments/assets/8a725f16-854e-478d-bf00-2b4282a0bb65)
![I%D~BM1}`$LLCN%S JXKOMW](https://github.com/user-attachments/assets/feea9829-a7fd-4629-aeb2-de82619766e1)

控制台里三个端口防火墙都开了
之前日志里提示token错误，然后刷新过一次token，把.env的对应处修改了

**Comment by ClayCoffee** [comment]
vtworayn里面当前服务的真连接延迟: -1 ms
根目录、status、list都能正常访问

**Comment by ClayCoffee** [comment]
config.json 
https://paste.ubuntu.com/p/96VsmVxTgS/

**Comment by k0baya** [comment]
https://github.com/k0baya/X-for-serv00?tab=readme-ov-file#%E6%9B%B4%E6%8D%A2-cloudflare-cdn-%E6%8E%A5%E5%85%A5%E7%82%B9

**Comment by ClayCoffee** [comment]
> https://github.com/k0baya/X-for-serv00?tab=readme-ov-file#%E6%9B%B4%E6%8D%A2-cloudflare-cdn-%E6%8E%A5%E5%85%A5%E7%82%B9

换过了，没用

**Comment by k0baya** [comment]
程序在运行就不是服务端的问题，请从你的客户端找问题，我无法给你提供帮助。

**Comment by k0baya** [comment]
`/control` 下有重启按钮，如果你有需要可以自己尝试。

**Comment by ClayCoffee** [comment]
{"status":"error", "message": "Incomplete response received from application"}

**Comment by ClayCoffee** [comment]
但是程序确实重启了
安卓上也没法连，提示 io read/write on closed pipe

**Comment by k0baya** [comment]
那就最好检查一下是否把 VL、VM、TR 的三个端口填错了。

**Comment by ClayCoffee** [comment]
uninstall是完全卸载吗？我重装下试试

**Comment by ClayCoffee** [comment]
> 那就最好检查一下是否把 VL、VM、TR 的三个端口填错了。

又看了一遍，没错

**Comment by k0baya** [comment]
如果你不介意，你可以把导出配置发到 `support@saika.free.hr` 这个邮箱，我试试我是否能够连接。

**Comment by ClayCoffee** [comment]
> 如果你不介意，你可以把导出配置发到 `support@saika.free.hr` 这个邮箱，我试试我是否能够连接。

谢谢了，新开了个机子，用一样的办法成了，可能是机子有问题？
