### ISSUE TITLE
求助大佬：不通过代理测延迟和测速都OK，启用代理后404

### ISSUE THREAD

**Issue by grcad** [k0baya/X-for-serv00#31]
![1234](https://github.com/user-attachments/assets/bddacb09-ab4e-47c5-b36c-ac82bf93979e)

**Comment by k0baya** [comment]
这三条线路，随便一条，发到这个邮箱，我试试看。
`support@saika.free.hr`

**Comment by grcad** [comment]
三条线路都已发，谢谢！

**Comment by k0baya** [comment]
我测试了一下，更换我本地优选的 cloudflare cdn 的 IP 后是能用的，但是延迟巨大。
![image](https://github.com/user-attachments/assets/2cf063b7-ad49-46fa-81c7-15d14aabf76c)
根据测试的 IP 可以判断你使用的是 S8，然后我看了一眼：
![image](https://github.com/user-attachments/assets/38f046e3-8cef-4b48-8ad4-7ab4bf54e84b)
可以发现 S8 长期都有大流量在跑，目测使用这个 Server 来部署代理服务器的人不在少数，所以应该是服务器本身的网络拥堵造成的。对于这种情况并没有太好的解决办法。你可以尝试使用其他 Server，比如 S0：
![image](https://github.com/user-attachments/assets/e9948796-6114-4b66-9f55-b8f138c255a2)
亦或者等待新的 Server —— S9开始放号。

**Comment by grcad** [comment]
好的，只要不是我在配置过程中出错就放心了，谢谢大佬！

**Comment by k0baya** [comment]
另外建议使用我的另外一个仓库进行测试：
https://github.com/k0baya/sb-for-serv00
Hysteria2 协议在服务器网络拥堵的情况下通常比其他协议表现更佳。

**Comment by grcad** [comment]
收到，迟些我会试一试的，有结果再来报告！

**Comment by k0baya** [comment]
关于你邮件提到的其他项目，经我对比，最大的区别是他的配置没有添加 IPv6。本项目特点之一就是添加 IPv6 的支持，这点是不能退让的，我已经重新对内置配置进行了尽可能的调优，但出于对 IPv6 的支持是通过二次代理实现这一点来讲，整体的速率是一定不如直接出站的。

但是，如果使用我前面说的我的另一项目，效果则完全不一样。一样也是支持 IPv6，效果如下：
使用 Cloudflare CDN 的 Vless-ws-tls：
![bdc75f752de2e3354557f453b9817dae](https://github.com/user-attachments/assets/dd4f347e-de5f-4623-9bda-93881ab37a23)
使用 TUIC 5 直连：
![fd75a7446a661859eec268f83f325655](https://github.com/user-attachments/assets/423f9f5c-e27d-4371-8a4c-055034494f9f)
今天调优配置后的本项目：
![c8c87cc801393cf47a44ba62031e80fc](https://github.com/user-attachments/assets/04ef1e8e-3079-430d-b2b7-ff27024c99c2)

以上测速均在移动 300 Mbps 宽带下进行。

**Comment by grcad** [comment]
我在部署sb-for-serv00时失败了，提示证书获取失败：
![777a](https://github.com/user-attachments/assets/c3a462ae-d005-42e8-ac9a-d480395056fe)
查看证书是否有效，却显示证书是有效的：
![777b](https://github.com/user-attachments/assets/20a736d8-5278-42f8-bf8c-04724d860bc7)
请教这是什么原因，谢谢！

**Comment by k0baya** [comment]
> 我在部署sb-for-serv00时失败了，提示证书获取失败： ![777a](https://private-user-images.githubusercontent.com/176554918/357283600-c3a462ae-d005-42e8-ac9a-d480395056fe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzIxMTksIm5iZiI6MTcyMzUzMTgxOSwicGF0aCI6Ii8xNzY1NTQ5MTgvMzU3MjgzNjAwLWMzYTQ2MmFlLWQwMDUtNDJlOC1hYzlhLWQ0ODAzOTUwNTZmZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QwNjUwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZmU1MzA5ZDllM2M5OGJhNzZkNGQwZDlmYzhjMGE2YTQ4MDc3YmYxYjUwZjM3ODg2ZmE2MDc5ZTIyNTk2MWY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qC_u2DOeLmdoBcVhBS7xKkLeZsRtRNXCc8NsWsM62S8) 查看证书是否有效，却显示证书是有效的： ![777b](https://private-user-images.githubusercontent.com/176554918/357283806-20a736d8-5278-42f8-bf8c-04724d860bc7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzIxMTksIm5iZiI6MTcyMzUzMTgxOSwicGF0aCI6Ii8xNzY1NTQ5MTgvMzU3MjgzODA2LTIwYTczNmQ4LTUyNzgtNDJmOC1iZjhjLTA0NzI0ZDg2MGJjNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QwNjUwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZmFiZWIyNDg2ZGVhOWFlNDM1MmIyODUzNGFkNjMxZDhiYWIzNDcyZjY4ZGJmMjJiZDI4ZGE0Yzg0OTAzYjliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1cmjTSsguGAlAltxHf5yismnVNh2bh3IzuLyCvqD4Tw) 请教这是什么原因，谢谢！

仔细阅读 readme，有获取证书的介绍，如果说不需要你申请的证书能够使用，我就不会在 readme 标出了。
另外，除了私密信息以外，不需要再发邮件，我会查看GitHub。

**Comment by grcad** [comment]
自述文件读过很多遍，也正是按照文件所述步骤一步一步操作的，但无论是全新申请的虚拟机，还是之前申请的虚拟机，操作下来都提示“The weekly certificate limit for the domain has been used”，但之前我从未在这些机器上申请过证书，所以我才去web端查看是否有有效证书。谢谢你提供的帮助，打扰了！

**Comment by k0baya** [comment]
![image](https://github.com/user-attachments/assets/72c02f16-169a-41a0-b754-f8686f8754ea)

**Comment by grcad** [comment]
新申请了域名，也在serv00下成功生成证书，并且也顺利完成了sb-for-serv00部署，遗憾的是真连接延迟测试结果为-1，测速提示“The SSL connection could not be established,see inner exception",前后折腾了三、四天，结果虽然不理想，但过程中学到了不少知识，谢谢！

**Comment by grcad** [comment]
今天重测，sb-for-serv00的节点竟然通了，速度还不错，谢大佬指导！
![777a](https://github.com/user-attachments/assets/fc083e18-b6f5-4ec0-b6f9-ccd9ac7cb3da)
