### ISSUE TITLE
list 文件未生成

### ISSUE THREAD

**Issue by shylock-wu** [k0baya/X-for-serv00#32]
首先进入`/status`查看 `web.js` 和 `cloudflare` 进程都是启动了的
但是 list 里面没东西
![CleanShot 2024-08-15 at 14 42 20](https://github.com/user-attachments/assets/54e93e36-c73d-48b7-8e02-2227d5778746)

**Comment by k0baya** [comment]
在你几乎没有提供任何信息，让我用算命的方法来诊断错误的情况下，我能想到的唯一一种复现你这个情况方法：
先查看`/list`再查看`/status`，进程起来以后还不清除浏览器缓存就直接返回`/list`查看信息。

我也只能建议你按照说明文件一步一步操作。

**Comment by shylock-wu** [comment]
感谢回复
