### ISSUE TITLE
目前改用其它CF的CDN接入点会连不上，目前只有最开始的这个可行

### ISSUE THREAD

**Issue by minecraftHCX** [k0baya/X-for-serv00#33]

**Comment by k0baya** [comment]
没太明白你是什么意思，只是想说默认的CDN接入点很好用么？

**Comment by minecraftHCX** [comment]
啊...抱歉我的表述有误，就是默认的CDN节点有点慢，我找的其它的CDN节点（直接是ip）替换上去就会连不上服务，不知道是不是CF的问题
不过代理脚本应该没问题，就是遇到点疑难杂症了_(:з」∠)_
________________________________
发件人: k0baya ***@***.***>
发送时间: 2024年8月24日 19:39
收件人: k0baya/X-for-serv00 ***@***.***>
抄送: minecraftHCX ***@***.***>; Author ***@***.***>
主题: Re: [k0baya/X-for-serv00] 目前改用其它CF的CDN接入点会连不上，目前只有最开始的这个可行 (Issue #33)


没太明白你是什么意思，只是想说默认的CDN接入点很好用么？

―
