### ISSUE TITLE
想请教关于serv00对程序的限制的一些问题

### ISSUE THREAD

**Issue by minecraftHCX** [k0baya/X-for-serv00#34]
“此次版本更新之后，X-for-Serv00 已经可以摆脱 Serv00 的 Crontab 启动”
请问serv00对所有脚本都是这种限制吗？我之前有个服务在一段时间不用后会莫名其妙宕机
感觉像是serv00关了，但是查询进程时又还在，就是不会有响应
这次想搞清楚serv00到底是怎么对程序进行限制的
求大佬解答

**Comment by k0baya** [comment]
Serv00 并未对脚本有什么限制，只是受限于机能，有时候进程会被挂起或者阻塞，甚至有时候会被“挤死”。且有时管理员会重启宿主机，所有进程都会被杀。
他们对于程序的限制就和你在面板中看到的一样，3 G 的磁盘空间、512 MB 的内存、20 个线程上限以及一定额度的 vCPU 分配。

**Comment by minecraftHCX** [comment]
> Serv00 并未对脚本有什么限制，只是受限于机能，有时候进程会被挂起或者阻塞，甚至有时候会被“挤死”。且有时管理员会重启宿主机，所有进程都会被杀。
> 他们对于程序的限制就和你在面板中看到的一样，3 G 的磁盘空间、512 MB 的内存、20 个线程上限以及一定额度的 vCPU 分配。

额...如果未超过任何限额的情况下依然会有挂起，阻塞或挤死的情况吗？

**Comment by k0baya** [comment]
> > Serv00 并未对脚本有什么限制，只是受限于机能，有时候进程会被挂起或者阻塞，甚至有时候会被“挤死”。且有时管理员会重启宿主机，所有进程都会被杀。
> > 他们对于程序的限制就和你在面板中看到的一样，3 G 的磁盘空间、512 MB 的内存、20 个线程上限以及一定额度的 vCPU 分配。
> 
> 额...如果未超过任何限额的情况下依然会有挂起，阻塞或挤死的情况吗？

当然会啊...因为主机配置就那么高，一台机器 10000 用户，实际上超额分配非常严重。

以 S10 为例，物理内存一共 190G，但是 10000 用户每人 0.5G 的配额。处理器和宽带更加寒酸——10000 人共享 24 核，10000 人共享 1000Mbps。就算你只有两三个进程，其他用户顶额开，这处理器这内存怎么可能顶得住呢？

如果没有超额分配，pm2 就不可能无法正常使用了。
