### ISSUE TITLE
最后的页面不显示添加证书的那个域名，显示默认的域名。。页面也加载不出来不知道为啥

### ISSUE THREAD

**Issue by pili-book** [k0baya/X-for-serv00#35]
直连版本，如何添加自己的域名了添加的时候如何选择
![image](https://github.com/user-attachments/assets/61a3faf4-a523-4583-af94-209882d14a70)
我现在把默认域名都删除了，但是还是显示的是那个默认域名

**Comment by k0baya** [comment]
脚本固定写的就是serv00默认自带域名，这个域名只需要用来监控保活以及获取一次配置，此后再无作用，你用自己的域名是有什么别的需求？

**Comment by pili-book** [comment]
> 脚本固定写的就是serv00默认自带域名，这个域名只需要用来监控保活以及获取一次配置，此后再无作用，你用自己的域名是有什么别的需求？
哦还以为是显示自己的域名了，这会能打开了。刚才各种打不开那个提示网页，生成的九个服务器vmess的显示延迟为-1，别的都显示有连接，不知道这个正常不，顺便问问需要安装PM2吗？好像PM2能保证进程不被杀

**Comment by pili-book** [comment]
> 脚本固定写的就是serv00默认自带域名，这个域名只需要用来监控保活以及获取一次配置，此后再无作用，你用自己的域名是有什么别的需求？
现在测试基本上都是-1，虽然实际上连接上是大部分都能用，哈，感谢，虽然我也搞不懂怎么回事

**Comment by k0baya** [comment]
不需要 pm2。本项目只要访问网页就可以唤醒+保活，你只需要按照 readme 去挂一个网站监控即可。测试为 -1 可能是你的客户端兼容性不太好，建议更换内核版本更新比较勤快的客户端。

**Comment by pili-book** [comment]
> 不需要 pm2。本项目只要访问网页就可以唤醒+保活，你只需要按照 readme 去挂一个网站监控即可。测试为 -1 可能是你的客户端兼容性不太好，建议更换内核版本更新比较勤快的客户端
网上看的有人说这服务器会后台自动重启这样子也能保活吗？

**Comment by k0baya** [comment]
注意我说的是唤醒+保活。本项目设计上就是重启或者进程被杀后可以被自动唤醒，平常自动监控进程列表并保活。
