### ISSUE TITLE
建议不要把三个端口都占满，以便于同时搭建其他服务

### ISSUE THREAD

**Issue by kero990** [k0baya/X-for-serv00#37]
serv00只能开3个端口，对于大部分自用来说，也不需要同时3协议，使用3端口
能否添加选项，用户自己选择使用的协议（数量），以保证不过多占用端口。

**Comment by k0baya** [comment]
Same as [sb-for-serv00 #11](https://github.com/k0baya/sb-for-serv00/issues/11#issuecomment-2308161830)
