### ISSUE TITLE
脚本中所用的cloudflared下载地址已被s7屏蔽

### ISSUE THREAD

**Issue by YoungerKayn** [k0baya/X-for-serv00#38]
![image](https://github.com/user-attachments/assets/fe086398-b463-4ecd-9965-432a85483f20)
如图

**Comment by k0baya** [comment]
https://github.com/k0baya/X-for-serv00?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

![image](https://github.com/user-attachments/assets/3c8db6f5-f1f1-4643-9e4e-8e20ddaa1068)

可以手动上传的，详情请查看 readme。
