### ISSUE TITLE
您好，大佬。请问运行start.sh报错怎么办，但是用lacalhost：port/list能访问节点部署细节

### ISSUE THREAD

**Issue by yanhaoyang0929** [k0baya/X-for-serv00#4]
以下是运行时报错code
~$ chmod +x start.sh && bash start.sh

up to date, audited 131 packages in 1s

17 packages are looking for funding
  run `npm fund` for details

2 moderate severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
appending output to nohup.out
 audit
# npm audit report

request  *
Severity: moderate
Server-Side Request Forgery in Request - https://github.com/advisories/GHSA-p8p7-x288-28g6
Depends on vulnerable versions of tough-cookie
No fix available
node_modules/request

tough-cookie  <4.1.3
Severity: moderate
tough-cookie Prototype Pollution vulnerability - https://github.com/advisories/GHSA-72xf-g2v4-qvf3
No fix available
node_modules/tough-cookie

2 moderate severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

**Comment by yanhaoyang0929** [comment]
![Uploading DFOX6T{SK5]6R67XS8`D{HW.png…]()

**Comment by yanhaoyang0929** [comment]
![DFOX6T{SK5 6R67XS8`D{HW](https://github.com/k0baya/X-for-serv00/assets/143801259/0b6b5a6d-6365-4779-bbbe-7bcae9c56505)

**Comment by k0baya** [comment]
请问你进行连接测试了吗？

**Comment by yanhaoyang0929** [comment]
> 请问你进行连接测试了吗？

您好，我测试了链接。但是我不是用原生的 username.serv00.net 域名搭建。
我使用 XX.username.serv00.net ——带有子域名的域名目录下搭建，请问可行吗？
感谢您的回复

**Comment by k0baya** [comment]
> > 请问你进行连接测试了吗？
> 
> 您好，我测试了链接。但是我不是用原生的 username.serv00.net 域名搭建。 我使用 XX.username.serv00.net ——带有子域名的域名目录下搭建，请问可行吗？ 感谢您的回复

你测试了连接，是通的就能用，不是通的就代表有地方没做对，你想问什么？

**Comment by kimlinea** [comment]
same issue not working. Using custom domain and cloudflare tunnel. You did not mention how to use the cloudflare command to install cloudflared service. I googled and found how to acquire the tunnel token and run the start.sh but some dependency and depreciated package issue same as the topic.

**Comment by k0baya** [comment]
> same issue not working. Using custom domain and cloudflare tunnel. You did not mention how to use the cloudflare command to install cloudflared service. I googled and found how to acquire the tunnel token and run the start.sh but some dependency and depreciated package issue same as the topic.

The reason I didn't mention how to use the cloudflare command is because the script takes care of it and simply requires you to fill in the relevant variables in the startup script `start.sh` without you having to do anything else manually.
The packages installation warning has no effect on the normal operation of this repository, what matters is whether it works after deployment.

**Comment by floydchase** [comment]
Installed with custom domain and cloudflare tunnel and aquired sub address but can't connect. Tried to replace the server address alejandracaiccedo.com with good cloudflare IP still can not connect.

**Comment by k0baya** [comment]
> Installed with custom domain and cloudflare tunnel and aquired sub address but can't connect. Tried to replace the server address alejandracaiccedo.com with good cloudflare IP still can not connect.

Could you please post your `start.sh` configuration?

**Comment by imbigyellow** [comment]
大佬 大佬 为什么我按步骤安装好后使用“IP:端口/list"打不开网页。我是个小白我问几个问题哈：1，是不是服务器里的IP要有证书.。2，WEBPORT和VMPORT是不是填写ser00里面打开的两个端口号码。3，WSPATH位置是不是可以不用改就serv00就可以。4，ARGO_AUTH，ARGO_DOMAIN这两个不填没事吧。如果愿意回答的话4个问题用y（yes）n（no）回答我就好yyyy/nnnn

**Comment by k0baya** [comment]
> 大佬 大佬 为什么我按步骤安装好后使用“IP:端口/list"打不开网页。我是个小白我问几个问题哈：1，是不是服务器里的IP要有证书.。2，WEBPORT和VMPORT是不是填写ser00里面打开的两个端口号码。3，WSPATH位置是不是可以不用改就serv00就可以。4，ARGO_AUTH，ARGO_DOMAIN这两个不填没事吧。如果愿意回答的话4个问题用y（yes）n（no）回答我就好yyyy/nnnn

不用HTTPS就不需要证书。

就是填你放行的端口，其中webport和字面意思一样是web服务的端口，vmport和字面意思一样是vmess的端口。

wspath我已经在readme说明了，你可以不修改使用默认值。

如果你不需要固定argo隧道，可以不填argo_auth和argo_domain这两个变量，我在readme应该已经说得很明白了。

**Comment by liangxietu** [comment]
> 大佬 大佬 为什么我按步骤安装好后使用“IP:端口/list"打不开网页。我是个小白我问几个问题哈：1，是不是服务器里的IP要有证书.。2，WEBPORT和VMPORT是不是填写ser00里面打开的两个端口号码。3，WSPATH位置是不是可以不用改就serv00就可以。4，ARGO_AUTH，ARGO_DOMAIN这两个不填没事吧。如果愿意回答的话4个问题用y（yes）n（no）回答我就好yyyy/nnnn

entrypoint.sh 文件里也有端口，可以进去编辑一下。改成对应的即可。

**Comment by k0baya** [comment]
> > 大佬 大佬 为什么我按步骤安装好后使用“IP:端口/list"打不开网页。我是个小白我问几个问题哈：1，是不是服务器里的IP要有证书.。2，WEBPORT和VMPORT是不是填写ser00里面打开的两个端口号码。3，WSPATH位置是不是可以不用改就serv00就可以。4，ARGO_AUTH，ARGO_DOMAIN这两个不填没事吧。如果愿意回答的话4个问题用y（yes）n（no）回答我就好yyyy/nnnn
> 
> entrypoint.sh 文件里也有端口，可以进去编辑一下。改成对应的即可。

如果不是完全明白自己在做什么，请一概在start.sh内修改环境变量。

**Comment by timmywong2003** [comment]
我也是用“IP:端口/list"打不开网页，start.sh我只改了export WEBPORT=9120，export VMPORT=26607，然后export UUID=填了自己的uuid，上传后运行，提示“Installing dependence......Please wait for a while.X-for-Serv00 is trying to start up, please visit http://:9120 to get the configuration.”。然后用“IP:端口/list"也是打不开，开vpn也打不开

**Comment by k0baya** [comment]
> 我也是用“IP:端口/list"打不开网页，start.sh我只改了export WEBPORT=9120，export VMPORT=26607，然后export UUID=填了自己的uuid，上传后运行，提示“Installing dependence......Please wait for a while.X-for-Serv00 is trying to start up, please visit http://:9120 to get the configuration.”。然后用“IP:端口/list"也是打不开，开vpn也打不开

请你按照readme中的方法找到ip地址，看看到底能不能打开网页，或者把你的ip+port贴出来。

**Comment by timmywong2003** [comment]
> > 我也是用“IP:端口/list"打不开网页，start.sh我只改了export WEBPORT=9120，export VMPORT=26607，然后export UUID=填了自己的uuid，上传后运行，提示“Installing dependence......Please wait for a while.X-for-Serv00 is trying to start up, please visit http://:9120 to get the configuration.”。然后用“IP:端口/list"也是打不开，开vpn也打不开
> 
> 请你按照readme中的方法找到ip地址，看看到底能不能打开网页，或者把你的ip+port贴出来。
刚才又试着运行了一下，网页弹出了用户名和密码，输入默认值之后过了很久，就显示“文件未生成”，是不是服务器本身的问题啊？

**Comment by liangxietu** [comment]
我的情况是根据教程做到最后启动，然后读进程，并没有开启代理，然后看了看entrypoint.sh文件，见到抬头定义里的两个端口都被赋予了固定的值3001和3002，然后我把这两个值改成对应自己设置的值，再运行就通了。

供参考。一切以的hub主的说明为准，感谢提供这些代码~

**Comment by k0baya** [comment]
由于 Cloudflare 临时隧道存在数量限制，现不推荐使用临时隧道运行本仓库，建议大家固定隧道使用。详见[#972](https://github.com/cloudflare/cloudflared/issues/972)

**Comment by t0mmy4** [comment]
> 我的情况是根据教程做到最后启动，然后读进程，并没有开启代理，然后看了看entrypoint.sh文件，见到抬头定义里的两个端口都被赋予了固定的值3001和3002，然后我把这两个值改成对应自己设置的值，再运行就通了。
> 
> 供参考。一切以的hub主的说明为准，感谢提供这些代码~

我按照readme里步骤弄完，然后把entrypoint里的两个端口改了也打不开网页😥

**Comment by liangxietu** [comment]
> > 我的情况是根据教程做到最后启动，然后读进程，并没有开启代理，然后看了看entrypoint.sh文件，见到抬头定义里的两个端口都被赋予了固定的值3001和3002，然后我把这两个值改成对应自己设置的值，再运行就通了。
> > 供参考。一切以的hub主的说明为准，感谢提供这些代码~
> 
> 我按照readme里步骤弄完，然后把entrypoint里的两个端口改了也打不开网页😥

不用改其他东西了，按照教程做一遍就好了，作者已经把文件都调试好了~~ 我刚刚重新删了跟着步骤重做一边，还把通道加了上去，都没问题的了~

**Comment by Myuuer** [comment]
同ip端口打不开
X-for-Serv00 is trying to start up, please visit http://128.204.223.119:37630 to get the configuration.
