### ISSUE TITLE
如何全局流量都走warp？

### ISSUE THREAD

**Issue by dinaau** [k0baya/X-for-serv00#40]
已经搭建成功 在 s11

status页面 有 ./cloudflared tunnel 

但是连接的时候还是显示波兰的 ip 31.186.87.205 并非 cloudflare的 ip

**Comment by k0baya** [comment]
全局 warp 很慢，为确保可用性我不可能默认设置默认全局 warp，故只有特定规则以及 IPv6 走 warp。
有需求的话你可以自己修改配置文件：`/home/LOGIN/domains/LOGIN.serv00.net/public_nodejs/config.json`
只需要修改其中的路由规则，请自行查阅文档按照需修改配置文件：[Project X](https://xtls.github.io/config/routing.html)

**Comment by dinaau** [comment]
> 全局 warp 很慢，为确保可用性我不可能默认设置默认全局 warp，故只有特定规则以及 IPv6 走 warp。 有需求的话你可以自己修改配置文件：`/home/LOGIN/domains/LOGIN.serv00.net/public_nodejs/config.json` 只需要修改其中的路由规则，请自行查阅文档按照需修改配置文件：[Project X](https://xtls.github.io/config/routing.html)

修改好后如何操作让他生效 ， 重启不了

**Comment by k0baya** [comment]
> > 全局 warp 很慢，为确保可用性我不可能默认设置默认全局 warp，故只有特定规则以及 IPv6 走 warp。 有需求的话你可以自己修改配置文件：`/home/LOGIN/domains/LOGIN.serv00.net/public_nodejs/config.json` 只需要修改其中的路由规则，请自行查阅文档按照需修改配置文件：[Project X](https://xtls.github.io/config/routing.html)
> 
> 修改好后如何操作让他生效 ， 重启不了

获取配置的网页`/control `路径，点击 restart 按钮，然后回到`/status`反复刷新，直到相关进程出现，则重启完成。
