### ISSUE TITLE
生成的订阅链接大多数软件都无法解析

### ISSUE THREAD

**Issue by bbylw** [k0baya/X-for-serv00#41]
订阅链接无法被识别，只能复制链接。影响一些不支持复制添加的客户端。希望能改进

**Comment by k0baya** [comment]
什么叫大多数软件都无法解析？不支持识别剪切板添加的软件原来还是大多数？你要怎么添加？

**Comment by bbylw** [comment]
就是订阅链接大部分工具都解析不出来，， 复制粘贴的工具支持hiddify v2rayn karing
 singbox这类不支持粘贴链接的就废了

**Comment by k0baya** [comment]
> 就是订阅链接大部分工具都解析不出来，， 复制粘贴的工具支持hiddify v2rayn karing singbox这类不支持粘贴链接的就废了

v2rayn 不支持读取剪切板？
![image](https://github.com/user-attachments/assets/75543656-7b53-4385-8855-f399e1c9dcfa)
订阅链接解析不出？
![image](https://github.com/user-attachments/assets/7e3c251d-cdfe-458d-a883-e2ab9c622a14)

你还是先回答一下这个问题：
> 你要怎么添加？
