### ISSUE TITLE
保活脚本应该如何写啊

### ISSUE THREAD

**Issue by bojur00** [k0baya/X-for-serv00#42]
这个应该是目前支持最多类型的项目，能否再教学一下保活具体应该怎么操作

**Comment by k0baya** [comment]
不需要你写脚本。按照readme操作不就行了么。
https://github.com/k0baya/X-for-serv00?tab=readme-ov-file#%E8%87%AA%E5%8A%A8%E5%90%AF%E5%8A%A8
![image](https://github.com/user-attachments/assets/6d33757b-c063-4e95-8ecd-aa6ddbc7279a)
