### ISSUE TITLE
自定 status页面登陆密码时候，如果选用admin作为登录用户名，那么无法识别自定义密码，必须使用默认密码password。如果要自定义密码，必须同时选择一个与自定义用户名不同的用户名。

### ISSUE THREAD

**Issue by bigbrave2008** [k0baya/X-for-serv00#44]
此外，如果使用argo隧道，其实不需要再控制面板里放行对应的端口。

**Comment by k0baya** [comment]
> 自定 status页面登陆密码时候，如果选用admin作为登录用户名，那么无法识别自定义密码，必须使用默认密码password。如果要自定义密码，必须同时选择一个与自定义用户名不同的用户名。

这个问题不可能存在，请你完全卸载重新尝试。

另外，不清楚你说的什么控制面板放行端口，因为关于端口放行的操作已经全部由脚本接管，Argo 隧道只需要去 cf 那边填入对应的隧道配置即可。

**Comment by bigbrave2008** [comment]
> > 自定 status页面登陆密码时候，如果选用admin作为登录用户名，那么无法识别自定义密码，必须使用默认密码password。如果要自定义密码，必须同时选择一个与自定义用户名不同的用户名。
> 
> 这个问题不可能存在，请你完全卸载重新尝试。
> 
> 另外，不清楚你说的什么控制面板放行端口，因为关于端口放行的操作已经全部由脚本接管，Argo 隧道只需要去 cf 那边填入对应的隧道配置即可。

试过好几次了，使用脚本的重置脚本处理的，然后重装，都是这样。包括x-for-serv00和sb-for-serv00都出现这个情况。

此外，端口就是说如果用argo隧道，脚本不用特意设着端口，就如附件，我其实手动在面板设置页面把脚本创建的端口删除了。argo隧道本身就是打隧道穿透的，不需要再设置端口

![截屏2024-10-10 21 53 38](https://github.com/user-attachments/assets/99473386-3719-41ad-b775-457a32be0a11)

**Comment by k0baya** [comment]
没端口权限，xray 核心无法运行，你知道自己在说什么吗？你删掉端口还能正常用，那是因为进程暂时还没被杀而已。
另外你提出来的问题我这里根本无法复现，应该是你一个人的问题。

**Comment by bigbrave2008** [comment]
OK清楚了。多谢
