### ISSUE TITLE
这个对cf的ssl模式有要求吗

### ISSUE THREAD

**Issue by bojur00** [k0baya/X-for-serv00#45]
选择灵活还是严格还是什么有影响吗，可以多路复用吗，那个sb的好像是可以的，这个好像不可以

**Comment by k0baya** [comment]
没有影响，原理上都是一模一样的，只不过这个仓库使用的 xray 核心，而那边是 sing-box 核心。

**Comment by bojur00** [comment]
好的，谢谢
