### ISSUE TITLE
大佬！进程启动成功，无法使用代理

### ISSUE THREAD

**Issue by SuperQiang1209** [k0baya/X-for-serv00#46]
![image](https://github.com/user-attachments/assets/c94cea9c-1137-47da-bdc1-bc1f69b227d1)

![image](https://github.com/user-attachments/assets/055400c6-f181-451f-a730-902c078f42ff)
![image](https://github.com/user-attachments/assets/a5fc20f3-364a-428a-a172-96b5b36eee18)
ws path确认配置正确

![image](https://github.com/user-attachments/assets/c5efaa81-2038-45f9-8909-45c977a6c30d)
![image](https://github.com/user-attachments/assets/ed80ac18-315d-46b1-9594-6e369871f9c4)
![image](https://github.com/user-attachments/assets/683f6f22-1512-4f86-9e2c-2e279117dc68)
大佬帮忙给看看啥问题

**Comment by SuperQiang1209** [comment]
![image](https://github.com/user-attachments/assets/5fc69e12-f82c-4b13-9310-2644a8379dfb)

**Comment by k0baya** [comment]
你随便贴其中一条配置出来我看看。

**Comment by SuperQiang1209** [comment]
```
vless://fd858008-0dcd-4a94-b766-4d26265fac83@upos-sz-mirrorcf1ov.bilivideo.com:443?path=%2Fserv00-vless%3Fed%3D2560&security=tls&encryption=none&host=wangwus.us.kg&type=ws&sni=wangwus.us.kg#Argo-k0baya-Vless
```

**Comment by k0baya** [comment]
你是不是三个argo_domain的环境变量写错了。你是单独使用的这个域名，而没有设置sub domain，对应的vless的端口吗？

**Comment by SuperQiang1209** [comment]
感谢大佬！确实是3个argo_domain都配置错了，叨扰大佬
