### ISSUE TITLE
保活是对这个脚本服务的吗？

### ISSUE THREAD

**Issue by zyhiderole** [k0baya/X-for-serv00#48]
还是针对 serv00账号的啊？
对账号是不是设置一周访问一次info
入股是对服务的话 一天访问两次info吗？

**Comment by k0baya** [comment]
保活是针对进程进行的。账号不回收的要求是每三个月登陆一次ssh/面板，可以直接在面板自带的cronjob中添加sshpass任务，循环周期设置在1个月到3个月之间。账号本身的不回收的要求太容易满足，没有必要进行过多的折腾。
