### ISSUE TITLE
进程和隧道都启动成功，但是真链接-1？？？？？？

### ISSUE THREAD

**Issue by PaperCupsRay** [k0baya/X-for-serv00#56]
![Uploading Snipaste_2024-12-19_11-07-30.png…]()
![Snipaste_2024-12-19_11-07-12](https://github.com/user-attachments/assets/e39f82f0-8dd2-46a0-978f-bfafd5ac3969)
![微信图片_20241219110611](https://github.com/user-attachments/assets/838d93fb-f277-4d16-955f-1c66edc7876a)

trojan://3a7545f4-dea3-407b-827d-1af9283728ae@upos-sz-mirrorcf1ov.bilivideo.com:443?security=tls&sni=tro.paperdream.us.kg&allowInsecure=1&type=ws&host=tro.paperdream.us.kg&path=%2Fserv00-trojan%3Fed%3D2560#Argo-k0baya-Trojan

劳烦大佬看看

**Comment by k0baya** [comment]
反正我于 UTC+8 16:42 查看 tro.paperdream.us.kg 域名的时候提示 Argo Tunnel 不在线。建议先自行检查。

**Comment by PaperCupsRay** [comment]
> 反正我于 UTC+8 16:42 查看 tro.paperdream.us.kg 域名的时候提示 Argo Tunnel 不在线。建议先自行检查。

serv00上进程被噶了。。。刚重启了，还是不行
![Uploading Snipaste_2024-12-19_16-56-54.png…]()
