### ISSUE TITLE
求助，都启动成功但真链接-1

### ISSUE THREAD

**Issue by neduic** [k0baya/X-for-serv00#57]
可以帮我看看吗
vless://c9b6be5c-7fd4-4c0a-a187-e3e59435c2a2@upos-sz-mirrorcf1ov.bilivideo.com:443?path=%2Fyinxir-vless%3Fed%3D2560&security=tls&encryption=none&host=14l.yinwr.ggff.net&type=ws&sni=14l.yinwr.ggff.net#Argo-k0baya-Vless
![Screenshot_2024-12-20-15-56-49-312_com v2ray ang](https://github.com/user-attachments/assets/bc8dc924-3f6b-4ecb-9557-a2373a3ae4ae)
![Screenshot_2024-12-20-15-57-36-533_com microsoft emmx canary](https://github.com/user-attachments/assets/57942a28-041e-42d8-b199-fad0387f4f9d)

**Comment by k0baya** [comment]
很神奇，我连了一下，能用，看这个 IP 地址应该是 s14
![Screenshot_2024-12-20-17-58-24-50_f31c5faf1ec54ae85e84c424b0049793](https://github.com/user-attachments/assets/c002c184-1cd2-415b-b7b0-6b632f5239a9)

**Comment by neduic** [comment]
> 很神奇，我连了一下，能用，看这个 IP 地址应该是 s14 ![Screenshot_2024-12-20-17-58-24-50_f31c5faf1ec54ae85e84c424b0049793](https://private-user-images.githubusercontent.com/132335755/397698616-c002c184-1cd2-415b-b7b0-6b632f5239a9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2OTEwNTAsIm5iZiI6MTczNDY5MDc1MCwicGF0aCI6Ii8xMzIzMzU3NTUvMzk3Njk4NjE2LWMwMDJjMTg0LTFjZDItNDE1Yi1iN2IwLTZiNjMyZjUyMzlhOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQxMDMyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMWRiZTUzYTdlMDllMWQxZWFiYTNlMjllZGJhMmUwNzI1MGVlMmQzZjFhNTI3NjZlODAwOTVjZTg4MmY2MTgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.huqQiishq7_j8Cex2Aa2wU8a81V9JHoTuYaz1gwfnuc)

那可能就是网络问题，我这里clash和v2ray都用不了

**Comment by neduic** [comment]
刚试了一下，在我这里好像google类的网站打不开。真链接-1也是因为用的谷歌的测延迟链接
